### ISSUE TITLE
Attestation procedure

### ISSUE THREAD

**Issue by chigarovae** [intel/tdx-tools#157]
Hi! First, thanks for your great work. Could you please describe how can an application running in your patched QEMU be attested remotely? Is it possible at all on the TDX level? Should any third-party solutions be used as when using Gramine SGX?

Thanks in advance!

**Comment by kenplusplus** [comment]
Thanks @chigarovae  Sure we will publish the complete steps soon for end-to-end attestation process.

**Comment by chigarovae** [comment]
@kenplusplus @dongx1x Hi! Any news on attestation?

**Comment by kenplusplus** [comment]
@chigarovae @dongx1x  @ruomengh I have added the "attestation" doc in the wiki https://github.com/intel/tdx-tools/wiki/TDX-End-to-End-Attestation
