### ISSUE TITLE
Build fails for Ubuntu TD

### ISSUE THREAD

**Issue by kkbodke** [intel/tdx-tools#165]
Build is failing for Ubuntu TD with the latest tdx-tools repo commit 3d7809db8c4d714d973e3959d1ece9bae241cee6

W: grub-efi-amd64-bin: debian-news-entry-has-strange-distribution UNRELEASED
W: grub-efi-amd64-bin: duplicate-override-context statically-linked-binary (lines 2 7) [usr/share/lintian/overrides/grub-efi-amd64-bin:7]
W: grub-efi-amd64-bin: duplicate-override-context statically-linked-binary (lines 3 8) [usr/share/lintian/overrides/grub-efi-amd64-bin:8]
W: grub-efi-amd64-bin: duplicate-override-context unstripped-binary-or-object (lines 1 6) [usr/share/lintian/overrides/grub-efi-amd64-bin:6]
W: grub-efi-amd64-bin: duplicate-override-context unstripped-binary-or-object (lines 4 9) [usr/share/lintian/overrides/grub-efi-amd64-bin:9]
W: grub-efi-amd64-dbg: duplicate-override-context statically-linked-binary (lines 2 5) [usr/share/lintian/overrides/grub-efi-amd64-dbg:5]
W: grub-efi-amd64-dbg: duplicate-override-context statically-linked-binary (lines 3 6) [usr/share/lintian/overrides/grub-efi-amd64-dbg:6]
W: grub-efi-amd64-dbg: duplicate-override-context unstripped-binary-or-object (lines 1 4) [usr/share/lintian/overrides/grub-efi-amd64-dbg:4]
W: grub-efi-amd64-bin: syntax-error-in-debian-changelog line 11 "badly formatted trailer line"
W: grub-efi-amd64-bin: syntax-error-in-debian-changelog line 13 "found start of entry where expected more change data or trailer"
W: grub-efi-amd64-bin: syntax-error-in-debian-changelog line 17 "badly formatted trailer line"
W: grub-efi-amd64-bin: syntax-error-in-debian-changelog line 19 "found start of entry where expected more change data or trailer"
W: grub-efi-amd64-bin: syntax-error-in-debian-changelog line 5 "badly formatted trailer line"
W: grub-efi-amd64-bin: syntax-error-in-debian-changelog line 7 "found start of entry where expected more change data or trailer"
W: grub-efi-amd64-bin: unknown-field Efi-Vendor
W: grub-efi-amd64: using-question-in-extended-description-in-templates grub-efi/install_devices_failed
N: 266 hints overridden (266 errors); 5 unused overrides
Finished running lintian.
+ cp grub-efi-amd64_2.06-mvp3_amd64.deb grub-efi-amd64-bin_2.06-mvp3_amd64.deb ../guest_repo/
+ cd ..
+ sudo apt remove grub2-build-deps-depends grub2-unsigned-build-deps-depends -y
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package grub2-build-deps-depends
+ true
+ build_kernel
+ cd intel-mvp-spr-kernel
./build-repo.sh: line 36: cd: intel-mvp-spr-kernel: No such file or directory

**Comment by jialeif** [comment]
@kkbodke Thank you for reporting this issue.
Should be solved in https://github.com/intel/tdx-tools/pull/163

**Comment by kkbodke** [comment]
Can you please confirm if it is merged to Master branch?

**Comment by jialeif** [comment]
Merged

**Comment by kkbodke** [comment]
Build fails still

+ cd ..
+ build_qemu
+ cd intel-mvp-tdx-qemu
./build-repo.sh: line 44: cd: intel-mvp-tdx-qemu: No such file or directory

**Comment by jialeif** [comment]
Yes, sorry for my mistake. Please correct https://github.com/intel/tdx-tools/blob/main/build/ubuntu-22.04/build-repo.sh#L44 to intel-mvp-tdx-qemu-kvm

**Comment by kkbodke** [comment]
patching file MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressHci.c
Hunk #1 FAILED at 789.
1 out of 1 hunk FAILED
dpkg-source: info: the patch has fuzz which is not allowed, or is malformed
dpkg-source: info: if patch '0001-MdeModulePkg-NvmExpressDxe-fix-check-for-Cap.Css.patch' is correctly applied by quilt, use 'quilt refresh' to update it
dpkg-source: info: if the file is present in the unpacked source, make sure it is also present in the orig tarball
dpkg-source: info: restoring quilt backup files for 0001-MdeModulePkg-NvmExpressDxe-fix-check-for-Cap.Css.patch
dpkg-source: error: LC_ALL=C patch -t -F 0 -N -p1 -u -V never -E -b -B .pc/0001-MdeModulePkg-NvmExpressDxe-fix-check-for-Cap.Css.patch/ --reject-file=- < tdx-tdvf-2022.ww39.4/debian/patches/0001-MdeModulePkg-NvmExpressDxe-fix-check-for-Cap.Css.patch subprocess returned exit status 1
