### ISSUE TITLE
Missing the CI build for Ubuntu Kernel

### ISSUE THREAD

**Issue by kenplusplus** [intel/tdx-tools#177]

**Comment by jialeif** [comment]
The ubuntu kernel build size exceeds github runner storage.

**Comment by kenplusplus** [comment]
![image](https://user-images.githubusercontent.com/31843217/198000545-cf92fde8-6cf2-4166-b57f-fb41459b4e38.png)
I added self-hosted runner for this project, so you can use "run-ons: self-hosted" to schedule build on our build server

**Comment by kenplusplus** [comment]
close with https://github.com/intel/tdx-tools/commit/557df1d76cb2fc224ea414bd537c8477b2a080ed
