### ISSUE TITLE
'tdx' not supported by KVM

### ISSUE THREAD

**Issue by fantas1a** [intel/tdx-tools#223]
Hi,

Could you please give me advice on possible reasons for the error 'qemu-system-x86_64: -accel kvm: kvm-type 'tdx' not supported by KVM' when I execute './start-qemu.sh -i td-guest-ubuntu-22.04.qcow2 -b grub'?

I use the version for ubuntu-22.04 and the mvp-tdx-5.15 branch. I follow the instruction for ubuntu 22.04 (https://github.com/intel/tdx-tools/tree/mvp-tdx-5.15/build/ubuntu-22.04). The detailed error information is as follows:

WARN: Using HVC console for grub, could not accept key input in grub menu
=========================================
Guest Image       : ./build/ubuntu-22.04/guest-image/td-guest-ubuntu-22.04.qcow2
Kernel binary     : 
OVMF_CODE         : /usr/share/qemu/OVMF_CODE.fd
OVMF_VARS         : /home/patrick/tdx-tools/OVMF_VARS.fd
VM Type           : td
CPUS              : 1
Boot type         : grub
Monitor port      : 9001
Enable vsock      : false
Enable debug      : false
Console           : HVC
=========================================
Remapping CTRL-C to CTRL-]
Launch VM:
/usr/bin/qemu-system-x86_64 -accel kvm -name process=tdxvm,debug-threads=on -m 2G -vga none -monitor pty -no-hpet -nodefaults -drive file=/home/patrick/tdx-tools/build/ubuntu-22.04/guest-image/td-guest-ubuntu-22.04.qcow2,if=virtio,format=qcow2 -monitor telnet:127.0.0.1:9001,server,nowait -device loader,file=/usr/share/qemu/OVMF_CODE.fd,id=fd0,config-firmware-volume=/home/patrick/tdx-tools/OVMF_VARS.fd -object tdx-guest,id=tdx -cpu host,-kvm-steal-time,pmu=off -machine q35,pic=no,kernel_irqchip=split,kvm-type=tdx,confidential-guest-support=tdx -device virtio-net-pci,netdev=mynet0 -smp 1 -netdev user,id=mynet0,hostfwd=tcp::10026-:22 -chardev stdio,id=mux,mux=on,logfile=/home/patrick/tdx-tools/vm_log_2023-01-05T1922.log -device virtio-serial,romfile= -device virtconsole,chardev=mux -monitor chardev:mux -serial chardev:mux -nographic
char device redirected to /dev/pts/5 (label compat_monitor0)
qemu-system-x86_64: -accel kvm: kvm-type 'tdx' not supported by KVM

**Comment by kenplusplus** [comment]
It might caused by many reasons:
1. Firstly, you might check whether TDX is enabled on the host correctly, see https://github.com/intel/tdx-tools/blob/main/doc/verify_tdx_host.md, 
2. Then check whether the qemu, KVM kernel, TDVF are compatible which comes from same release. You can get history tag from https://github.com/intel/tdx-tools/tags

**Comment by fantas1a** [comment]
> It might caused by many reasons:
> 
> 1. Firstly, you might check whether TDX is enabled on the host correctly, see https://github.com/intel/tdx-tools/blob/main/doc/verify_tdx_host.md,
> 2. Then check whether the qemu, KVM kernel, TDVF are compatible which comes from same release. You can get history tag from https://github.com/intel/tdx-tools/tags

May I know in the history tag link (https://github.com/intel/tdx-tools/tags), which release can be used with a lower version kernel?
