### ISSUE TITLE
What's the intel-mvp-tdx-qemu-kvm for?

### ISSUE THREAD

**Issue by fantas1a** [intel/tdx-tools#224]
Hi, I wonder what the intel-mvp-tdx-qemu-kvm/kernel/libvert/guest-shim/guest-grub2 in [tdx-tools](https://github.com/intel/tdx-tools)/[build](https://github.com/intel/tdx-tools/tree/main/build)/[ubuntu-22.04](https://github.com/intel/tdx-tools/tree/main/build/ubuntu-22.04)/ are for.

And in what order should I install them (concerning the given steps in [tdx-tools](https://github.com/intel/tdx-tools)/[build](https://github.com/intel/tdx-tools/tree/main/build)/[ubuntu-22.04](https://github.com/intel/tdx-tools/tree/main/build/ubuntu-22.04)/)?

I did not see an introduction for these files, and I wonder if it is connected to my building & running error.

Thank you.

**Comment by jialeif** [comment]
Hi, taking 2022ww49 as example, the [build-repo.sh](https://github.com/intel/tdx-tools/blob/2022ww49/build/ubuntu-22.04/build-repo.sh) outputs 2 folder guest_repo and host_repo. 
host_repo includes TDX enabled kernel, qemu-kvm, ovmf and libvirt. All these packages should be installed to the ubuntu host.
```
libvirt0_8.6.0-2022.11.17.mvp1_amd64.deb
libvirt-clients_8.6.0-2022.11.17.mvp1_amd64.deb
libvirt-daemon_8.6.0-2022.11.17.mvp1_amd64.deb
libvirt-daemon-config-network_8.6.0-2022.11.17.mvp1_all.deb
libvirt-daemon-config-nwfilter_8.6.0-2022.11.17.mvp1_all.deb
libvirt-daemon-driver-lxc_8.6.0-2022.11.17.mvp1_amd64.deb
libvirt-daemon-driver-qemu_8.6.0-2022.11.17.mvp1_amd64.deb
libvirt-daemon-system_8.6.0-2022.11.17.mvp1_amd64.deb
libvirt-daemon-system-systemd_8.6.0-2022.11.17.mvp1_all.deb
libvirt-login-shell_8.6.0-2022.11.17.mvp1_amd64.deb
linux-headers-5.19.0-mvp10v1+11_5.19.0-mvp10v1+11.tdx_all.deb
linux-headers-5.19.0-mvp10v1+11-generic_5.19.0-mvp10v1+11.tdx_amd64.deb
linux-image-unsigned-5.19.0-mvp10v1+11-generic_5.19.0-mvp10v1+11.tdx_amd64.deb
linux-modules-5.19.0-mvp10v1+11-generic_5.19.0-mvp10v1+11.tdx_amd64.deb
linux-modules-extra-5.19.0-mvp10v1+11-generic_5.19.0-mvp10v1+11.tdx_amd64.deb
ovmf_2022.11.9-0be81a4.mvp4_all.deb
qemu-system-common_7.0.50+mvp5+12_amd64.deb
qemu-system-data_7.0.50+mvp5+12_all.deb
qemu-system-x86_7.0.50+mvp5+12_amd64.deb
```
guest_repo includes TDX enabled kernel. Grub and shim are for TDX measurement, optional.
At least the kernel is required in a TDX VM. You can install it via `sudo apt install ./linux-*.deb`
```
grub-efi-amd64_2.06-mvp3_amd64.deb
grub-efi-amd64-bin_2.06-mvp3_amd64.deb
linux-headers-5.19.0-mvp10v1+11_5.19.0-mvp10v1+11.tdx_all.deb
linux-headers-5.19.0-mvp10v1+11-generic_5.19.0-mvp10v1+11.tdx_amd64.deb
linux-image-unsigned-5.19.0-mvp10v1+11-generic_5.19.0-mvp10v1+11.tdx_amd64.deb
linux-modules-5.19.0-mvp10v1+11-generic_5.19.0-mvp10v1+11.tdx_amd64.deb
shim_15.4-mvp3_amd64.deb
```
