### ISSUE TITLE
Error when running the start-qemu.sh in tdx host machine 

### ISSUE THREAD

**Issue by hasinidilanka** [intel/tdx-tools#227]
Hi All,

I am getting an error 'qemu-system-x86_64: -accel kvm: failed to initialize kvm: No such device' when I execute './start-qemu.sh -i td-guest-ubuntu-22.04.qcow2 -b grub'?

I am using ubuntu-22.04 and the mvp-tdx-5.15 branch and followed the instructions for ubuntu 22.04 (https://github.com/intel/tdx-tools/tree/mvp-tdx-5.15/build/ubuntu-22.04). 

I have also enabled virtualization in the machines through the BIOS. It seems like the issue is with running QEMU inside another virtualization. Could you please help me with this issue? 

**./start-qemu.sh -i td-guest-ubuntu-22.04.qcow2 -b grub**
```
WARN: Using HVC console for grub, could not accept key input in grub menu
=========================================
Guest Image       : td-guest-ubuntu-22.04.qcow2
Kernel binary     : 
OVMF_CODE         : /usr/share/qemu/OVMF_CODE.fd
OVMF_VARS         : /home/hasini/Desktop/tdx-tools/OVMF_VARS.fd
VM Type           : td
CPUS              : 1
Boot type         : grub
Monitor port      : 9001
Enable vsock      : false
Enable debug      : false
Console           : HVC
=========================================
Remapping CTRL-C to CTRL-]
Launch VM:
/usr/bin/qemu-system-x86_64 -accel kvm -name process=tdxvm,debug-threads=on -m 2G -vga none -monitor pty -no-hpet -nodefaults -drive file=/home/hasini/Desktop/tdx-tools/td-guest-ubuntu-22.04.qcow2,if=virtio,format=qcow2 -monitor telnet:127.0.0.1:9001,server,nowait -device loader,file=/usr/share/qemu/OVMF_CODE.fd,id=fd0,config-firmware-volume=/home/hasini/Desktop/tdx-tools/OVMF_VARS.fd -object tdx-guest,id=tdx -cpu host,-kvm-steal-time,pmu=off -machine q35,pic=no,kernel_irqchip=split,kvm-type=tdx,confidential-guest-support=tdx -device virtio-net-pci,netdev=mynet0 -smp 1 -netdev user,id=mynet0,hostfwd=tcp::10026-:22 -chardev stdio,id=mux,mux=on,logfile=/home/hasini/Desktop/tdx-tools/vm_log_2023-01-25T1323.log -device virtio-serial,romfile= -device virtconsole,chardev=mux -monitor chardev:mux -serial chardev:mux -nographic
char device redirected to /dev/pts/1 (label compat_monitor0)
ioctl(KVM_CREATE_VM) failed: 19 No such device
qemu-system-x86_64: -accel kvm: failed to initialize kvm: No such device
```

When I check whether the TDX is enabled in the host machine I am getting this message:

**sudo dmesg | grep -i TDX**
```
[    0.000000] Linux version 5.15.0-mvp16v11+0-generic  (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #mvp16v11+tdx SMP Wed Jan 11 16:24:50 EST 2023
[    0.125235] tdx-tests: bp_hit: 19
[    0.125235] tdx-tests: ovf_hit: 21
[    0.125235] tdx-tests: PASS: single step #VE emulated instructions
[    0.125235] tdx-tests: PASS: single step TDX module emulated CPUID 0
[    0.125235] tdx-tests: PASS: single step TDX module emulated RDMSR 0x1a0
```

Does this means TDX is enable in the host machine?

**Comment by kenplusplus** [comment]
Sound like the TDX SEAM module was not loaded successful, please refer the steps at https://github.com/intel/tdx-tools/blob/main/doc/verify_tdx_host.md

**Comment by hasinidilanka** [comment]
Which step should I follow in the document [()]( https://github.com/intel/tdx-tools/tree/main/build/ubuntu-22.04 ) to set up the TDX SEAM module?

**Comment by hasinidilanka** [comment]
Thank you for the pointers. For CentOS (Rhel-8) I suppose we can use the dracut. If I try to setup TDX on CentOS will I be able to use the SEAM module without any modifications?

**Comment by kenplusplus** [comment]
yes, centOS stream and RHEL are almost compabile. :-)
