### ISSUE TITLE
Is there a way to simulate a TDX capable CPU?

### ISSUE THREAD

**Issue by ReichertL** [intel/tdx-tools#228]
When trying to setup TDX tools I encountered a issue similar to  #223:
```
./start-qemu.sh -i td-guest-ubuntu-22.04.qcow2 -b grub
   ....
qemu-system-x86_64: -accel kvm: vm-type X86_TDX_VM not supported by KVM
```
The problem according to the response in issue  #223 seems to be that I do not have a CPU with TDX. As far as I know no such CPUs have been released for the public yet.

Is there another way how I can emulate/simulate TDX?  I do have a computer with a SGX 1.0 capable CPU.   
If there is documentation in this regard I must have missed it. 

Thank you for your help.

**Comment by kenplusplus** [comment]
Sorry, I do not know how to simulate/emulate TDX.

**Comment by ReichertL** [comment]
Thanks for your fast response. 
I just found issue #86, so I guess not much has changed since then. So I guess I can only wait until Azure or one of the other cloud providers makes TDX available for end users some time this year.
