### ISSUE TITLE
Secret migration in TDX

### ISSUE THREAD

**Issue by ReichertL** [intel/tdx-tools#231]
Hello,
I have a general question about the functionalities of TDX as I could not find the corresponding information in the docs. 
In SGX, the enclave author was allowed to move secrets between two of their own enclaves. As I understand, this was mainly to facilitate updates to enclaves. 
Does this feature still exist in TDX? For containers, it might still be useful.
I appreciate your help.

**Comment by kenplusplus** [comment]
You may check chapter 13, "service TD" in new "[Intel® TDX Module v1.5 Base Architecture Specification](https://cdrdv2.intel.com/v1/dl/getContent/733575)" at https://www.intel.com/content/www/us/en/developer/articles/technical/intel-trust-domain-extensions.html

**Comment by ReichertL** [comment]
Thanks a lot. I will take a look at this section of the documentation.
