### ISSUE TITLE
What is TDX supported platform?

### ISSUE THREAD

**Issue by X1anWang** [intel/tdx-tools#234]
Hi,

I use ubuntu 22.04 on my Intel(R) Xeon(R) CPU E3-1280 v6 @ 3.90GHz. Following [instruction for Ubuntu](https://github.com/intel/tdx-tools/tree/main/build/ubuntu-22.04), I pass all steps but do not test the guest image successfully in the last step. It prompted:

qemu-system-x86_64: -accel kvm: vm-type X86_TDX_VM not supported by KVM

Then I follow the 'dmesg | grep -i TDX' in [verify_tdx_host.md](https://github.com/intel/tdx-tools/blob/main/doc/verify_tdx_host.md). It shows:

[    0.000000] Linux version 5.19.0-mvp12v2+2-generic (sean@rdma17) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #mvp12v2+tdx SMP PREEMPT_DYNAMIC Thu Feb 9 07:52:57 UTC 2023
[    0.292060] KVM-debug: PASS: single step TDX module emulated CPUID 0
[    0.292060] KVM-debug: PASS: single step TDX module emulated RDMSR 0x1a0
[   16.735980] tdx: Cannot enable TDX on TDX disabled platform

May I know what is the pre-requirement for running the Github repo? And where can I refer to for the TDX abled/disabled platform?

Thank you very much!

**Comment by kenplusplus** [comment]
So you need get TDX enabled platform + CPU from Intel sale representative.
