### ISSUE TITLE
Legacy VM tested instead of TDVM

### ISSUE THREAD

**Issue by jurobystricky** [intel/tdx-tools#263]
The test  " test_tdvm_bridge_network_ip" in the file "test_tdvm_network.py"
actually tests a Legacy VM, not a TDVM.

https://github.com/intel/tdx-tools/blob/main/tests/tests/test_tdvm_network.py#L65

**Comment by ruomengh** [comment]
Thanks Juro for pointing it out. This has been fixed in PR#285.
