### ISSUE TITLE
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

### ISSUE THREAD

**Issue by HuangMinming** [intel/tdx-tools#271]
Hi, I built it on ubuntu 22.04. I ran "./build-repo.sh", after a long time , it failed. The last few log is below.
By the way, it needs at least 45GB disk space and takes a long time to build. I think it's better to be written in document.

dpkg-buildpackage: info: host architecture amd64
dpkg-source: info: using options from mvp-tdx-qemu-7.0.50/debian/source/options: --extend-diff-ignore=^capstone/|^dtc/|^slirp/|^meson/|^roms/.*/|^\.git-submodule-status$
 fakeroot debian/rules clean
echo '# autogenerated file, please edit debian/control-in' > debian/control.tmp
sed -e 's/^:ubuntu://' \
	-e '/^:[a-z]*:/D' debian/control-in >> debian/control.tmp
mv -f debian/control.tmp debian/control
chmod -w debian/control
dh_testdir
rm -rf b
find scripts/ -name '*.pyc' -delete || :
find: ‘scripts/’: No such file or directory
rm -f debian/qemu-user.1
rm -f configs/devices/x86_64-softmmu/microvm.mak
dh_clean
 debian/rules build
make: *** No rule to make target 'configure', needed by 'b/qemu/configured'.  Stop.
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b failed

My machine info:
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

**Comment by jialeif** [comment]
Sure, it's better to add the storage requirement.
I did not see this error while build qemu-kvm, can you clean qemu-kvm build dir and try building qemu-kvm separately?
> cd build/ubuntu-22.04/intel-mvp-tdx-qemu-kvm/
> ./build.sh

**Comment by HuangMinming** [comment]
I rebuilt it successfully. When I ran ./tdx-guest-stack.sh, it failed. Below is the output, please help me, thank you.

smu@smu-vm:~/tdx/tdx-tools/build/ubuntu-22.04/guest-image$ ./tdx-guest-stack.sh
+ export LIBGUESTFS_BACKEND=direct
+ LIBGUESTFS_BACKEND=direct
+++ readlink -f ./tdx-guest-stack.sh
++ dirname /home/smu/tdx/tdx-tools/build/ubuntu-22.04/guest-image/tdx-guest-stack.sh
+ THIS_DIR=/home/smu/tdx/tdx-tools/build/ubuntu-22.04/guest-image
+ IMG_URL=https://cloud-images.ubuntu.com/jammy/current
+ CLOUD_IMG=jammy-server-cloudimg-amd64.img
+ TD_IMG=td-guest-ubuntu-22.04.qcow2
+ REPO_NAME=guest_repo
+ REPO_LOCAL=/home/smu/tdx/tdx-tools/build/ubuntu-22.04/guest-image/../guest_repo
+ [[ ! -d /home/smu/tdx/tdx-tools/build/ubuntu-22.04/guest-image/../guest_repo ]]
+ command -v virt-customize
/usr/bin/virt-customize
+ [[ ! -f jammy-server-cloudimg-amd64.img ]]
+ wget https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
--2023-04-07 19:13:50--  https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
Resolving cloud-images.ubuntu.com (cloud-images.ubuntu.com)... 185.125.190.37, 185.125.190.40, 2620:2d:4000:1::17, ...
Connecting to cloud-images.ubuntu.com (cloud-images.ubuntu.com)|185.125.190.37|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 684654592 (653M) [application/octet-stream]
Saving to: ‘jammy-server-cloudimg-amd64.img’

jammy-server-cloudi 100%[===================>] 652.94M  18.8MB/s    in 39s     

2023-04-07 19:14:30 (16.9 MB/s) - ‘jammy-server-cloudimg-amd64.img’ saved [684654592/684654592]

+ cp jammy-server-cloudimg-amd64.img td-guest-ubuntu-22.04.qcow2
+ virt-customize -a td-guest-ubuntu-22.04.qcow2 --root-password password:123456
[   0.0] Examining the guest ...
virt-customize: error: libguestfs error: /usr/bin/supermin exited with 
error status 1.
To see full error messages you may need to enable debugging.
Do:
  export LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1
and run the command again.  For further information, read:
  http://libguestfs.org/guestfs-faq.1.html#debugging-libguestfs
You can also run 'libguestfs-test-tool' and post the *complete* output
into a bug report or message to the libguestfs mailing list.

If reporting bugs, run virt-customize with debugging enabled and include 
the complete output:

  virt-customize -v -x [...]
smu@smu-vm:~/tdx/tdx-tools/build/ubuntu-22.04/guest-image$

**Comment by HuangMinming** [comment]
I rebuilt it successfully. But when I ran "./start-qemu.sh -i td-guest-ubuntu-22.04.qcow2 -b grub", it failed. My cpu does not support tdx, is it a problem?

sudo ./start-qemu.sh -i ./build/ubuntu-22.04/guest-image/td-guest-ubuntu-22.04.qcow2 -b grub
Create /home/smu/tdx/tdx-tools/OVMF.fd from template /usr/share/qemu/OVMF.fd
WARN: Using HVC console for grub, could not accept key input in grub menu
=========================================
Guest Image       : ./build/ubuntu-22.04/guest-image/td-guest-ubuntu-22.04.qcow2
Kernel binary     : 
OVMF              : /home/smu/tdx/tdx-tools/OVMF.fd
VM Type           : td
CPUS              : 1
Boot type         : grub
Monitor port      : 9001
Enable vsock      : false
Enable debug      : false
Console           : HVC
=========================================
Remapping CTRL-C to CTRL-]
Launch VM:
/usr/bin/qemu-system-x86_64 -accel kvm -name process=tdxvm,debug-threads=on -m 2G -vga none -monitor pty -no-hpet -nodefaults -drive file=/home/smu/tdx/tdx-tools/build/ubuntu-22.04/guest-image/td-guest-ubuntu-22.04.qcow2,if=virtio,format=qcow2 -monitor telnet:127.0.0.1:9001,server,nowait -bios /home/smu/tdx/tdx-tools/OVMF.fd -object tdx-guest,sept-ve-disable,id=tdx -cpu host,-kvm-steal-time,pmu=off -machine q35,kernel_irqchip=split,confidential-guest-support=tdx -device virtio-net-pci,netdev=mynet0 -smp 1 -netdev user,id=mynet0,hostfwd=tcp::10026-:22 -chardev stdio,id=mux,mux=on,logfile=/home/smu/tdx/tdx-tools/vm_log_2023-04-07T1946.log -device virtio-serial,romfile= -device virtconsole,chardev=mux -monitor chardev:mux -serial chardev:mux -nographic
qemu-system-x86_64: -object tdx-guest,sept-ve-disable,id=tdx: warning: short-form boolean option 'sept-ve-disable' deprecated
Please use sept-ve-disable=on instead
char device redirected to /dev/pts/3 (label compat_monitor0)
qemu-system-x86_64: -accel kvm: vm-type X86_TDX_VM not supported by KVM

**Comment by kenplusplus** [comment]
could you please check "rdsmr -f 11:11 0x1401" please refer https://github.com/intel/tdx-tools/wiki/1.-Linux-Stack-for-Intel%C2%AE-TDX#validate-host-status

**Comment by HuangMinming** [comment]
> rdsmr -f 11:11 0x1401

My cpu is intel core, and does not support tdx. 
"sudo rdmsr -f 11:11 0x1401" command outputs is 0.

**Comment by jialeif** [comment]
Hi Minming,
I add your suggestion in https://github.com/intel/tdx-tools/issues/271
You can create a pull request directly for any idea. 
Thank you!

**Comment by jialeif** [comment]
> > Reference in new issu
> 
> Thank you. If I don't have a computer with cpu that support tdx, how can I run the image?

You can start a non-TD VM.
./start-qemu.sh -i td-guest-ubuntu-22.04.qcow2 -b grub - t efi

**Comment by HuangMinming** [comment]
> > > Reference in new issu
> > 
> > 
> > Thank you. If I don't have a computer with cpu that support tdx, how can I run the image?
> 
> You can start a non-TD VM. ./start-qemu.sh -i td-guest-ubuntu-22.04.qcow2 -b grub -t efi

Thank you. It works.
