### ISSUE TITLE
vm-type X86_TDX_VM not supported by KVM (Ubuntu 22.04) 

### ISSUE THREAD

**Issue by Eggwane** [intel/tdx-tools#281]
Hi,
 
I followed all the instructions of the ```build/ubuntu-22.04/ README.md``` and got everything well built but then I'm getting this error while running the command ```./start-qemu.sh -i td-guest-ubuntu-22.04.qcow2 -b grub``` . 

```
qemu-system-x86_64: -accel kvm: vm-type X86_TDX_VM not supported by KVM
```

I tried to change the path of the qemu binary in order to use the one I built : ``` QEMU_EXEC="~/projects/tdx-tools/build/ubuntu-22.04/intel-mvp-tdx-qemu-kvm/mvp-tdx-qemu-v7.2.0/b/qemu/qemu-system-x86_64" ``` but the error remains.

Am I not using the good KVM stack somehow? The ```lsmod``` command shows that the ```kvm``` and ```kvm_intel``` modules are loaded though.

Thanks in advance for your help.

**Comment by Eggwane** [comment]
Ok my bad, I thought it was a repo for simulation but apparently there's no way to get any hardware nor simulation like we could with SGX as mentioned in [#86 ](https://github.com/intel/tdx-tools/issues/86#issuecomment-1125110608) and #249.

**Comment by wenhuizhang** [comment]
same error here
