### ISSUE TITLE
Error occur when launching a TD VM with custom VM MAC address via start-qemu.sh

### ISSUE THREAD

**Issue by zhlsunshine** [intel/tdx-tools#289]
Hi,

An error happens when launching a TD VM with custom VM MAC address via `start-qemu.sh`, the command may be like below:

```
./start-qemu.sh -i td-guest-ubuntu-22.04.qcow2 -k vmlinuz -r /dev/vda1 -m 52:54:98:76:54:32
```

The output of the error is below:
![image](https://user-images.githubusercontent.com/4101246/234503235-596b8d9f-340d-4dc2-834b-1cd71fa8701c.png)

**Comment by jialeif** [comment]
Thank you for reporting the issue.
