### ISSUE TITLE
Need to support custom ip addresses for multiple TD VMs

### ISSUE THREAD

**Issue by zhlsunshine** [intel/tdx-tools#291]
Hi,
I need to create a k8s cluster with multiple TD VMs in my use case. However, no matter how many TD VMs I launch, the IP and MAC addresses of `enp0s1` always are `10.0.2.15` and `52:54:00:12:34:56`.  Therefore, I can not successfully deploy the kubernetes cluster with these TD VMs via `start-qemu.sh`.

**Comment by jialeif** [comment]
Hi @zhlsunshine,
Thank you for contributing new function in start_qemu.sh .
We prefer to use libvirt to mange VMs for complex jobs. Please see https://github.com/intel/tdx-tools/blob/main/doc/launch_td_guest.md#launch-via-libvirt

**Comment by zhlsunshine** [comment]
Hi @jialeif, sure, thanks for your recommendation!
