### ISSUE TITLE
Build does not do an incremental build

### ISSUE THREAD

**Issue by kkbodke** [intel/tdx-tools#308]
If for some reason, the first build fails, and fix the error and re-issue the build, it is building all the packages from the beginning, which is time consuming.
Can the build check for the already built packages and skip rebuilding the same and continue to build where it failed?

**Comment by kenplusplus** [comment]
This is very nice suggestion, thanks @kkbodke

**Comment by kenplusplus** [comment]
jialei already fixed this at commit https://github.com/intel/tdx-tools/commit/ac11804bd98012e32e9f7293ff0a4b283d996305 @kkbodke could you please help to retry. Thanks!
