### ISSUE TITLE
W5-2445 support

### ISSUE THREAD

**Issue by matti** [intel/tdx-tools#329]
If I purchase $3000usd hp z4 g5 workststion with the entry level  W5-2445 processor, will TDX tooling work on it?

Eg. can I run secure VMs on it? Are all sapphire rapids cpus okay for this?

**Comment by kenplusplus** [comment]
TDX tools should work on all "TDX capabile and enabled" Xeon server. Please download our recent white paper https://www.intel.com/content/www/us/en/content-details/780133/whitepaper-linux-stacks-for-intel-trust-domain-extension-1-0.html and run https://github.com/intel/tdx-tools/blob/main/utils/check-tdx-host.sh to check whether your platform support TDX.

**Comment by matti** [comment]
Basically no Sapphire Rapids supports TDX - Emerald Rapids will, see https://github.com/intel/tdx-tools/issues/399
