### ISSUE TITLE
w3-2423 support

### ISSUE THREAD

**Issue by matti** [intel/tdx-tools#330]
what about the most entry level w3-2423 - related #329

**Comment by kenplusplus** [comment]
TDX tools should work on all "TDX capabile and enabled" Xeon server. Please download our recent white paper https://www.intel.com/content/www/us/en/content-details/780133/whitepaper-linux-stacks-for-intel-trust-domain-extension-1-0.html and run https://github.com/intel/tdx-tools/blob/main/utils/check-tdx-host.sh to check whether your platform support TDX.

**Comment by matti** [comment]
Basically no Sapphire Rapids supports TDX - Emerald Rapids will, see https://github.com/intel/tdx-tools/issues/399
