### ISSUE TITLE
can guest vm verify tdx

### ISSUE THREAD

**Issue by matti** [intel/tdx-tools#331]
Can guest vm know if it's being run in TDX?

Eg. if azure claims that the machine is TDX enabled, how can I be sure?

**Comment by kenplusplus** [comment]
Good suggestion, we will provide a simple script to check tdx guest status, @intelzhongjie  @ruomengh  could you please help that?

**Comment by matti** [comment]
from *inside* of the vm?

**Comment by kenplusplus** [comment]
> from _inside_ of the vm?

yes

**Comment by matti** [comment]
This script does not check if the guest is running as a secure vm - it only checks what /proc has - it's possible to fake /proc contents

**Comment by kenplusplus** [comment]
/proc comes from CPUID, but either CPUID could be fake. Within the TDX guest, I did not know other approach can check. 
From the host, you can dump guest memory..

**Comment by matti** [comment]
@kenplusplus I read the pdf you linked in another issue and isn't this described there as some attestation thing? Almost 50% of the pages address this "how can vm verify the trust"

**Comment by intelzhongjie** [comment]
Attestation is indeed a formal way to do the check if that's the requirement. Some more work is needed for that than current quick simple status check: https://github.com/intel/tdx-tools/pull/333

**Comment by matti** [comment]
@kenplusplus but, I can create /dev/tdx-guest device node in any qemu/kvm machine even without TDX enabled cpu and fake it.

**Comment by kenplusplus** [comment]
The key point is not /dev/tdx-guest, the key point is TDVMCALL instruction

**Comment by matti** [comment]
@kenplusplus okay but can you elaborate on that - why can't I implement custom TDVMCALL on non tdx-enabled host hardware?

**Comment by kenplusplus** [comment]
The TDCALL instruction is handled by SEAM module, which is signed by OEM PCH key as an ACM module. It handled by micro-code, so other could not implement it.

![image](https://github.com/intel/tdx-tools/assets/31843217/90352e2d-3a74-4985-973e-7b95a6eb32b2)

**Comment by matti** [comment]
so what I am looking for:

1. a vm is started on hostile host machine
2. vm downloads binary from my url
3. vm runs this binary and verifies SOMEHOW that this environment is secure despite the hostile host machine
4. vm posts this proof to my url
5. my url responds with confidential data
6. vm processes this confidential data

so what's the sauce for SOMEHOW here?

**Comment by kenplusplus** [comment]
> but if I somebody still implements it, how can I verify the signature?

1. it is CPU instruction, so somebody can only create their own CPU... 
2. also when do TDREPORT for remote attestion, the TDREPORT include CPU/PCH/SEAM signature. So remote replying party will verify whether it is a geninue environment.

**Comment by matti** [comment]
> it is CPU instruction, so somebody can only create their own CPU...

But isn't it possible to modify qemu so that I'll create my own CPU instruction?

**Comment by kenplusplus** [comment]
> > it is CPU instruction, so somebody can only create their own CPU...
> 
> But isn't it possible to modify qemu so that I'll create my own CPU instruction?

but you could not get a geninue Quote from TDREPORT, which including measurement and CPU version which signed by SGX attestation key.

**Comment by matti** [comment]
@kenplusplus okay got it thanks - now can you provide a sample on this verification? I read the linked pdf and it does not contain a concrete example on how to do this.

**Comment by kenplusplus** [comment]
Please check the chapter 4.3 attestation from the white paper at https://www.intel.com/content/www/us/en/content-details/780133/whitepaper-linux-stacks-for-intel-trust-domain-extension-1-0.html

After generating the quote, following command could be used to verify quote

$ git clone https://github.com/intel/SGXDataCenterAttestationPrimitives.git
$ cd SGXDataCenterAttestationPrimitives/SampleCode/TDQuoteVerificationSample
$ make DEBUG=1
$ ./app -quote <PATH>/quote.dat

You might take a look at source code like https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/4cb5c8b81f126f9aa3ee921d7980a909a9bd676d/QuoteVerification/QuoteVerificationService/src/qvl/VerifyQuoteWorker.cpp#L34

**Comment by kenplusplus** [comment]
> @kenplusplus awesome, I'll get my tdx hardware next week

Good news! Good luck. Hope tdx-tools can really help you.
