### ISSUE TITLE
Can I create an independent OS image and Kernel image for the guest

### ISSUE THREAD

**Issue by darragh-walker** [intel/tdx-tools#338]
I was wondering if it was possible to create an OS image and a Kernel vmlinuz image for the guest without having to do complete the entire build-repo.sh script. I think I've gotten it to create an operating system image correctly but when I run the build.sh script in the  intel-mvp-tdx-kernel directory there is no vmlinuz file generated from what I can see.
Thanks in advance,
Darragh.

**Comment by darragh-walker** [comment]
Hi Ken,
Thanks for the quick reply , steps would be great. I'm trying to setup the guest environment for use in a reference application to avoid the need for downloading private versions of the image. I got the image and kernel generated for centos using the 2022ww44 tag but cant seem to use the same method for ubuntu in the guest-image branch

**Comment by kenplusplus** [comment]
> Hi Ken, Thanks for the quick reply , steps would be great. I'm trying to setup the guest environment for use in a reference application to avoid the need for downloading private versions of the image. I got the image and kernel generated for centos using the 2022ww44 tag but cant seem to use the same method for ubuntu in the guest-image branch

centos is deprecated.

**Comment by kenplusplus** [comment]
@darragh-walker I am trying to enhance the guest-image tool at PR https://github.com/intel/tdx-tools/pull/347 could you please help a quick review? Thanks!

**Comment by matti** [comment]
@darragh-walker what hardware are you using?

**Comment by darragh-walker** [comment]
Hi, Sorry I was OOO until after the issue was closed, I'm testing the new main now and have managed to get the qcow2 file using the script for ubuntu but I'm still not sure how to get the vmlinuz file. @jialeif I was wondering if you could talk me through it if possible I have already run the build.sh file in the intel-mvp-tdx-kernel directory. Any help would be much appreciated.

**Comment by jialeif** [comment]
@darragh-walker you can get it from build directory:
find build/ubuntu-22.04/intel-mvp-tdx-kernel/ -name vmlinuz*
The vmlinuz file is like build/ubuntu-22.04/intel-mvp-tdx-kernel/mvp-tdx-kernel-v6.2/debian/linux-image-unsigned-6.2.0-mvp10v1+8-generic/boot/vmlinuz-6.2.0-mvp10v1+8-generic
or from deb package:
cd build/ubuntu-22.04/intel-mvp-tdx-kernel
dpkg -x ./linux-image-unsigned-6.2.0-mvp10v1+8-generic_6.2.0-mvp10v1+8.tdx_amd64.deb my-kernel
ls my-kernel/boot/vmlinuz-*
or from qcow2 image:
virt-get-kernel -a td*.qcow2
