### ISSUE TITLE
Add more checks for TD guest in utils/check-tdx-guest.sh

### ISSUE THREAD

**Issue by kenplusplus** [intel/tdx-tools#342]
By default, there are following items in TD guest:
1. CCEL table: at /sys/firmware/acpi/tables/
2. tdx-guest device node at /dev/tdx-guest

**Comment by intelzhongjie** [comment]
Please review https://github.com/intel/tdx-tools/pull/361

**Comment by kenplusplus** [comment]
Thanks @intelzhongjie
