### ISSUE TITLE
SGX is deprecated and not available in majority of Sapphire Rapids

### ISSUE THREAD

**Issue by matti** [intel/tdx-tools#351]
Running `utils/check-tdx-host.sh` gives me

<img width="577" alt="image" src="https://github.com/intel/tdx-tools/assets/3893/75f8e640-074f-448b-a16f-895eafd166fb">

Isn't SGX deprecated? I can't find any place to enable it in Asus Pro WS W790E-SAGE SE latest bios.

This is all "SGX" there is:

<img width="806" alt="image" src="https://github.com/intel/tdx-tools/assets/3893/9eef4bf6-2179-4716-95d1-26311536c8ed">

And at https://www.intel.com/content/www/us/en/products/sku/233484/intel-xeon-w32423-processor-15m-cache-2-10-ghz/specifications.html

<img width="767" alt="image" src="https://github.com/intel/tdx-tools/assets/3893/24e3b5aa-89e3-4267-acae-c826eb301779">

Same with for example https://ark.intel.com/content/www/us/en/ark/products/233481/intel-xeon-w52445-processor-26-25m-cache-3-10-ghz.html

**Comment by kenplusplus** [comment]
Is this helpful? https://www.intel.com/content/www/us/en/architecture-and-technology/software-guard-extensions-processors.html

**Comment by matti** [comment]
@kenplusplus so in other words, are you saying that the majority of sapphire rapids processors are not TDX compatible at all?

**Comment by kenplusplus** [comment]
> @kenplusplus so in other words, are you saying that the majority of sapphire rapids processors are not TDX compatible at all?

Sorry, I do not know the product features definition or timeline. For SGX, I think at least you can refer above official link. TDX feature depends on SGX.

**Comment by matti** [comment]
In this project you consistently refer and point to vague white papers - stop doing this.

Instead, list the concrete CPUs that *will* support tdx-tools.

**Comment by kenplusplus** [comment]
> In this project you consistently refer and point to vague white papers - stop doing this.
> 
> Instead, list the concrete CPUs that _will_ support tdx-tools.

Understand your point, thanks for your feedback. I have no more information about product or feature here. Could you please contact the vendor or sale representee on this?

**Comment by matti** [comment]
Which CPUs are you using to test tdx-tools?

**Comment by kenplusplus** [comment]
Sorry to bring frustration to you. But I am not the correct person to answer product infomration. 
I used the process followed by [What Intel® Xeon Processors Support for Intel® Trust Domain Extensions (Intel® TDX)?
](https://www.intel.com/content/www/us/en/support/articles/000091103/processors.html?wapkw=TDX)

**Comment by matti** [comment]
I am asking for what CPUs is the team using to test tdx-tools internally. It's a reasonable ask.

**Comment by kenplusplus** [comment]
> I am asking for what CPUs is the team using to test tdx-tools internally. It's a reasonable ask.

sorry, I could not share internal information here.

**Comment by matti** [comment]
So only a handful of Xeons might work - for example Intel Xeon Bronze 3408U and Xeon Silver 4410Y

Most of the sapphire rapids cpus just won't work because of the missing SGX.

This is, before I purchase Intel Xeon Bronze 3408U and learn that there is something else missing.

Related #353
