### ISSUE TITLE
No Sapphire Rapids Xeon supports TDX outside of major hyperscalers

### ISSUE THREAD

**Issue by matti** [intel/tdx-tools#399]
TDX support is coming in Emerald Rapids: https://www.techpowerup.com/304114/intel-xeon-sapphire-rapids-to-be-quickly-joined-by-emerald-rapids-granite-rapids-and-sierra-forest-in-the-next-two-years

The README is misleading with "Please contact Intel sales representative for on-premise bare metal server or processor or please refer What Intel® Xeon Processors Support for Intel® Trust Domain Extensions (Intel® TDX)?" - there is *no* server or processor that anybody else than a major cloud vendor has access to.

**Comment by kenplusplus** [comment]
@matti we updated README.md for hardware availability, please take a look.

**Comment by matti** [comment]
@kenplusplus looks good. Now I just wonder why *I* needed to push so hard on this to get a straight answer.

**Comment by TaihuLight** [comment]
@kenplusplus Apart of `4th Gen Intel Xeon Scalable processors`, does Intel Core processors like i7-10700K and i7-13700K support TDX?
As its specifications contains "Intel® Trusted Execution Technology" , Or this refers to SGX?

**Comment by matti** [comment]
@TaihuLight only upcoming xeon cpus will support.

**Comment by matti** [comment]
and yes, that refers to SGX

**Comment by TaihuLight** [comment]
Intel Trusted Execute Technology means Intel TXT instead of Intel SGX.
