### ISSUE TITLE
Broken link in documentation (guest image setup)

### ISSUE THREAD

**Issue by anselmolsm** [intel/tdx-tools#429]
Customer reported that at https://github.com/intel/tdx-tools/tree/tdx-1.5/tests#create-guest-image (also applicable to main branch) there's a broken link about guest image setup: https://github.com/intel/tdx-tools/blob/main/doc/create_guest_image.md

**Comment by kenplusplus** [comment]
Thanks @anselmolsm !

**Comment by ruomengh** [comment]
The issue has been fixed in PR #442. Thanks.
