### ISSUE TITLE
build/ubuntu-22.04/guest-image/create-ubuntu-image.sh - Error

### ISSUE THREAD

**Issue by kkbodke** [intel/tdx-tools#436]
create-ubuntu-image.sh is failing for tag 2023ww27, even after installing pytdxmeasure ptyhon package.

python3 -m pip install pytdxmeasure
Defaulting to user installation because normal site-packages is not writeable
Collecting pytdxmeasure
  Downloading pytdxmeasure-0.0.9-py3-none-any.whl (24 kB)
Requirement already satisfied: wheel in /usr/lib/python3/dist-packages (from pytdxmeasure) (0.37.1)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from pytdxmeasure) (59.6.0)
Installing collected packages: pytdxmeasure
Successfully installed pytdxmeasure-0.0.9

sudo ./create-ubuntu-image.sh -r ../guest_repo/ -f -s 25

/bin/python3: No module named pip
virt-customize: error: python3 -m pip install pytdxmeasure: command exited 
with an error

If reporting bugs, run virt-customize with debugging enabled and include 
the complete output:

  virt-customize -v -x [...]

**Comment by jialeif** [comment]
Fixed in https://github.com/intel/tdx-tools/commit/d3532ad7b97eb9bd501ab9dcb139206b501b4e31 on main branch.
Refer to https://github.com/intel/tdx-tools/issues/423
