### ISSUE TITLE
TDX GPU support

### ISSUE THREAD

**Issue by wdsun1008** [intel/tdx-tools#440]
We are working on confidential computing applications and would like to inquire if TDX supports the use of GPUs, such as PCI passthrough. We are aware that Nvidia's Hooper GPU now supports features related to confidential computing. However, using non-CC GPUs may compromise the security of confidential virtual machines (DMA). Nevertheless, we would like to understand if this potentially less secure approach can still be viable, as it would enable wider usage of confidential virtual machines, especially in the era of LLM.

**Comment by kenplusplus** [comment]
For TDX1.0/1.5, the IO is not in TCB. So all IO communiction need go with SWIOTB in virtio approach. It is hard to say less security.
From high level point, TDX 1.0/1.5 should support NVIDIA GPU or any otherwise GPU via passthrough (still go with bounce buffer). But I heard it maybe some detail issues need fix. I do not have a try. 
So if you met with some specific issue, please free to raise to us.

**Comment by wdsun1008** [comment]
> For TDX1.0/1.5, the IO is not in TCB. So all IO communictions need go with SWIOTB in virtio approach. It is hard to say less secure. From high level point, TDX 1.0/1.5 should able to support NVIDIA GPU or any other GPU via passthrough (still go with bounce buffer). But I heard it maybe some detail issues need to be fixed. I do not have a try. So if you met with some specific issue, please free to raise to us.

Thank you very much. We will conduct testing once the TDX hardware is in place. Currently, we have encountered several issues when testing on the AMD platform with Nvidia non-CC GPU. I am not a professional kernel and driver developer, but we are eager to leverage confidential computing capabilities in the AI era. Thank you again for your response. I will close this issue for now, but we are more than willing to contribute if there are any advancements.

**Comment by matti** [comment]
hey @wdsun1008 - I believe we are working on the same problem - would be nice to connect, feel free to email me at matti.paksula@iki.fi
