### ISSUE TITLE
Build fails with intel-mvp-tdx-guest-shim for Ubuntu22.04 when we trying build-repo for intel tdx

### ISSUE THREAD

**Issue by ajsagar14** [intel/tdx-tools#456]
When we try to run ./build-repo.sh script for the Ubuntu 22.04 I get the lot of error in relation to the intel-mvp-tdx-guest-shim a nd the kernel does not build successfully:

install: WARNING: ignoring --strip-program option as -s option was not specified
install: WARNING: ignoring --strip-program option as -s option was not specified
install: WARNING: ignoring --strip-program option as -s option was not specified
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -d -m 0755 /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -d -m 0700 /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/boot/efi/
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -d -m 0755 /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/boot/efi/EFI/BOOT/
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -d -m 0755 /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/boot/efi/EFI/ubuntu/
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -d -m 0755 /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/usr/lib/shim
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -m 0700 shimx64.efi /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/boot/efi/EFI/BOOT//BOOTX64.EFI
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -m 0700 shimx64.efi /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/boot/efi/EFI/ubuntu//
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -m 0700 shimx64.efi /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/usr/lib/shim/
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -m 0700 BOOTX64.CSV /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/boot/efi/EFI/ubuntu//
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -m 0700 BOOTX64.CSV /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/usr/lib/shim/
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -m 0644 fbx64.efi /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/boot/efi/EFI/BOOT//
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -m 0700 fbx64.efi /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/usr/lib/shim/
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -m 0644 mmx64.efi /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/boot/efi/EFI/BOOT//
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -m 0644 mmx64.efi /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/boot/efi/EFI/ubuntu//
install: WARNING: ignoring --strip-program option as -s option was not specified
install --strip-program=true -m 0700 mmx64.efi /root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/tmp/usr/lib/shim/
install: WARNING: ignoring --strip-program option as -s option was not specified
make: Leaving directory '/root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4'
rm -rf debian/tmp/usr/src
rm -rf debian/tmp/boot/efi/EFI/BOOT/BOOT*.EFI
make[1]: Leaving directory '/root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4'
   dh_install
/root/Documents/tdx-tools-2023ww27/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/shim.install: 1: /usr/lib/shim: Permission denied
dh_install: warning: debian/shim.install is marked executable but does not appear to an executable config.
dh_install: warning:
dh_install: warning: If debian/shim.install is intended to be an executable config file, please ensure it can
dh_install: warning: be run as a stand-alone script/program (e.g. "./debian/shim.install")
dh_install: warning: Otherwise, please remove the executable bit from the file (e.g. chmod -x "debian/shim.install")
dh_install: warning:
dh_install: warning: Please see "Executable debhelper config files" in debhelper(7) for more information.
dh_install: warning:
dh_install: error: debian/shim.install (executable config) returned exit code 126
make: *** [debian/rules:38: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -I -b failed
[root@c240-m7emr:~/Documents/tdx-tools-2023ww27/build/ubuntu-22.04#](mailto:root@c240-m7emr:~/Documents/tdx-tools-2023ww27/build/ubuntu-22.04#)

**Comment by jialeif** [comment]
hi, most shim build failures are due to incomplete source sync.
can you try:
```
rm -rf intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4
./build.sh
```

For the kernel, there is a patch on main, https://github.com/intel/tdx-tools/commit/c6c5a5925b7bffe8589ffedfe8066d44748e595c
please apply it to see if fixes the build.

**Comment by ajsagar14** [comment]
> hi, most shim build failures are due to incomplete source sync. can you try:
> 
> ```
> rm -rf intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4
> ./build.sh
> ```
> 
> For the kernel, there is a patch on main, [c6c5a59](https://github.com/intel/tdx-tools/commit/c6c5a5925b7bffe8589ffedfe8066d44748e595c) please apply it to see if fixes the build.

**Comment by ajsagar14** [comment]
> > hi, most shim build failures are due to incomplete source sync. can you try:
> > ```
> > rm -rf intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4
> > ./build.sh
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For the kernel, there is a patch on main, [c6c5a59](https://github.com/intel/tdx-tools/commit/c6c5a5925b7bffe8589ffedfe8066d44748e595c) please apply it to see if fixes the build.

**Comment by ajsagar14** [comment]
> hi, most shim build failures are due to incomplete source sync. can you try:
> 
> ```
> rm -rf intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4
> ./build.sh
> ```
> 
> For the kernel, there is a patch on main, [c6c5a59](https://github.com/intel/tdx-tools/commit/c6c5a5925b7bffe8589ffedfe8066d44748e595c) please apply it to see if fixes the build.


Tried the kernel patch [c6c5a59], but no luck observing the below error while running .build.sh


root@c240-m7emr:~/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel# ./build.sh
+ UPSTREAM_GIT_URI=https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
+ UPSTREAM_TAG=v5.19.17
+++ readlink -f ./build.sh
++ dirname /root/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel/build.sh
+ CURR_DIR=/root/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel
+ SOURCE_DIR=/root/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel/mvp-tdx-kernel-v5.19.17
+ PATCHSET=/root/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel/../../common/patches-tdx-kernel-MVP-KERNEL-5.19.17-v4.0.tar.gz
++ grep Ubuntu /etc/os-release
+ [[ PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu" == '' ]]
+ pushd /root/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel
~/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel ~/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel
+ get_source
+ echo 'Get upstream source code...'
Get upstream source code...
+ [[ ! -d /root/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel/mvp-tdx-kernel-v5.19.17 ]]
+ git clone -b v5.19.17 --single-branch --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git /root/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel/mvp-tdx-kernel-v5.19.17
Cloning into '/root/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel/mvp-tdx-kernel-v5.19.17'...
fatal: unable to access 'https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/': Failed to connect to git.kernel.org port 443 after 130233 ms: Connection timed out
root@c240-m7emr:~/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel#

**Comment by jialeif** [comment]
git has network issue on the host environment. You may need to config the proxy for it.
```
git config --global http.proxy <your_http_proxy>
git config --global https.proxy <your_https_proxy> 
git clone -b v5.19.17 --single-branch --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git
```

**Comment by ajsagar14** [comment]
> 

but my network is working fine and also i could able to login into the github  https://github.com/intel/tdx-tools/commit/c6c5a5925b7bffe8589ffedfe8066d44748e595c from firefox and download the tdx-tools

**Comment by jialeif** [comment]
Yes, your system network config is fine, and it's applied to Firefox.
From your log, it does not work for git in Terminal.

**Comment by ajsagar14** [comment]
> Yes, your system network config is fine, and it's applied to Firefox. From your log, it does not work for git in Terminal.

resolved git issue with the shared commands and again tried ./build.sh 
observed below errors 

    vmw_vsock_vmci_transport / hv_sock              : net-pf-40
    vmw_vsock_vmci_transport / vsock_loopback       : net-pf-40
make: *** [debian/rules.d/2-binary-arch.mk:200: /root/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel/mvp-tdx-kernel-v5.19.17/debian/stamps/stamp-install-generic] Error 1
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -b failed
root@c240-m7emr:~/Documents/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/tdx-tools-c6c5a5925b7bffe8589ffedfe8066d44748e595c/build/ubuntu-22.04/intel-mvp-tdx-kernel#

**Comment by jialeif** [comment]
ok, can you share the full build log via email?

**Comment by ajsagar14** [comment]
> ok, can you share the full build log via email?

sure email id ?

**Comment by jialeif** [comment]
In my profile. or try pasting the key logs here.

**Comment by ajsagar14** [comment]
> > ok, can you share the full build log via email?
> 
> sure email id ?

shared complete errors details through email 
thanks jialeif

**Comment by jialeif** [comment]
Hello Shimoga,
Got your build log.
You are using 2023ww27 for TDX 1.5 with kernel v6.2.16. From the log, the tdx-tools repo is switched to TDX 1.0 with kernel v5.19.17.
Let me cherry-pick the kernel fix patch to TDX 1.5 and send the TDX 1.5 branch later.

**Comment by jialeif** [comment]
@ajsagar14 https://github.com/intel/tdx-tools/commit/0fe3fa393437ed97c6d87dd4ffc840141f2c6526 has been merged for tdx-1.5.
Please use tdx-1.5 branch for kernel build:
```
git clone https://github.com/intel/tdx-tools -b tdx-1.5
cd tdx-tools/build/ubuntu-22.04/intel-mvp-tdx-kernel/
./build.sh
```

**Comment by ajsagar14** [comment]
> 

Hi Jialeif,
i was trying install ./pkg-builder build.re

**Comment by ajsagar14** [comment]
> @ajsagar14 [0fe3fa3](https://github.com/intel/tdx-tools/commit/0fe3fa393437ed97c6d87dd4ffc840141f2c6526) has been merged for tdx-1.5. Please use tdx-1.5 branch for kernel build:
> 
> ```
> git clone https://github.com/intel/tdx-tools -b tdx-1.5
> cd tdx-tools/build/ubuntu-22.04/intel-mvp-tdx-kernel/
> ./build.sh
> ```

i was trying to install build-repo.sh on ubuntu after installing docker ,
i am observing the below error while running build-repo.sh 

rm -rf debian/tmp/usr/src
rm -rf debian/tmp/boot/efi/EFI/BOOT/BOOT*.EFI
make[1]: Leaving directory '/root/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4'
   dh_install
/root/build/ubuntu-22.04/intel-mvp-tdx-guest-shim/mvp-tdx-guest-shim-15.4/debian/shim.install: 1: /usr/lib/shim: not found
dh_install: warning: debian/shim.install is marked executable but does not appear to an executable config.
dh_install: warning:
dh_install: warning: If debian/shim.install is intended to be an executable config file, please ensure it can
dh_install: warning: be run as a stand-alone script/program (e.g. "./debian/shim.install")
dh_install: warning: Otherwise, please remove the executable bit from the file (e.g. chmod -x "debian/shim.install")
dh_install: warning:
dh_install: warning: Please see "Executable debhelper config files" in debhelper(7) for more information.
dh_install: warning:
dh_install: error: debian/shim.install (executable config) returned exit code 127
make: *** [debian/rules:38: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -I -b failed
root@ajith:/home/ajith/Documents/tdx-tools-tdx-1.5/build/ubuntu-22.04#

**Comment by jialeif** [comment]
If build in docker via pkg-builder, regarding your environment docker proxy is also needed.

**Comment by ajsagar14** [comment]
Sure jialei,
But we are observing below errors while installing build-repo.sh and rhel and ubuntu and I could not able resolve these

dh_install: warning:
dh_install: error: debian/shim.install (executable config) returned exit code 127
make: *** [debian/rules:38: binary] Error 25
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -us -uc -ui -i -I -b failed
***@***.***:/home/ajith/Documents/tdx-tools-tdx-1.5/build/ubuntu-22.04#

**Comment by jialeif** [comment]
hi, what should I call you.
Are you running ./build-repo.sh or ./pkg-builder build-repo.sh?

**Comment by ajsagar14** [comment]
Hi Jialei,

I am running ./pkg-builder build-repo.sh but not  sucessfull  

error: package `clap_builder v4.4.0` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.67.0-nightly
Either upgrade to rustc 1.70.0 or newer, or use
cargo update -p ***@***.*** --precise ver
where `ver` is the latest version of `clap_builder` supporting rustc 1.67.0-nightly


Regards
Ajith Sagar

**Comment by jialeif** [comment]
Hi Sagar,
The build error due to recent rust updates for clap 4.4.0 and clap_lex 0.5.1, which requires rustc 1.70.0.
We'll update the code. The workaround is to limit the versions of clap < 4.4 and clap_lex 0.5.0 in deps/td-shim/td-shim-tools/Cargo.toml.
The issue is also reported in https://github.com/confidential-containers/td-shim/issues/583.

Regards,
Jialei

**Comment by jialeif** [comment]
@ajsagar14 please check the hotfix using https://github.com/intel/tdx-tools/tree/2023ww27-update
