### ISSUE TITLE
Please specify supported CPUs in the README table

### ISSUE THREAD

**Issue by bktan8** [intel/tdx-tools#458]
It would be very helpful to know which CPU is supported for each Tag/TDX Version in this table.

![image](https://github.com/intel/tdx-tools/assets/29260389/5c4befca-a5be-4983-af1b-5ad592d8e401)

**Comment by kenplusplus** [comment]
Thanks comments, we have got legal approved message at "https://github.com/intel/tdx-tools#12-hardware-availability", we could not disclose any product information here.
