### ISSUE TITLE
build-repo.sh with 2023WW27 SW stack failed on RHEL 8.7

### ISSUE THREAD

**Issue by lianghouxu** [intel/tdx-tools#476]
Run build-repo.sh with 2023WW27 on RHEL 8.7. meet the following error:

$ cargo run -p td-shim-tools --bin td-shim-ld --no-default-features --features=linker /kvmdata/code/tdx-tools/build/rhel-8/intel-mvp-tdx-migration/rpmbuild/BUILD/migtd/deps/td-shim/target/x86_64-unknown-none/release/ResetVector.bin /kvmdata/code/tdx-tools/build/rhel-8/intel-mvp-tdx-migration/rpmbuild/BUILD/migtd/deps/td-shim/target/x86_64-unknown-none/release/td-shim -p /kvmdata/code/tdx-tools/build/rhel-8/intel-mvp-tdx-migration/rpmbuild/BUILD/migtd/target/x86_64-unknown-none/release/migtd -o /kvmdata/code/tdx-tools/build/rhel-8/intel-mvp-tdx-migration/rpmbuild/BUILD/migtd/target/release/migtd.bin -m /kvmdata/code/tdx-tools/build/rhel-8/intel-mvp-tdx-migration/rpmbuild/BUILD/migtd/config/metadata.json
**error: package `clap v4.4.2` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.67.0-nightly**
Either upgrade to rustc 1.70.0 or newer, or use
cargo update -p clap@4.4.2 --precise ver
where `ver` is the latest version of `clap` supporting rustc 1.67.0-nightly
thread 'main' panicked at 'Fail to build migtd binary: command exited with non-zero code `cargo run -p td-shim-tools --bin td-shim-ld --no-default-features --features=linker /kvmdata/code/tdx-tools/build/rhel-8/intel-mvp-tdx-migration/rpmbuild/BUILD/migtd/deps/td-shim/target/x86_64-unknown-none/release/ResetVector.bin /kvmdata/code/tdx-tools/build/rhel-8/intel-mvp-tdx-migration/rpmbuild/BUILD/migtd/deps/td-shim/target/x86_64-unknown-none/release/td-shim -p /kvmdata/code/tdx-tools/build/rhel-8/intel-mvp-tdx-migration/rpmbuild/BUILD/migtd/target/x86_64-unknown-none/release/migtd -o /kvmdata/code/tdx-tools/build/rhel-8/intel-mvp-tdx-migration/rpmbuild/BUILD/migtd/target/release/migtd.bin -m /kvmdata/code/tdx-tools/build/rhel-8/intel-mvp-tdx-migration/rpmbuild/BUILD/migtd/config/metadata.json`: 101', xtask/src/main.rs:28:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/var/tmp/rpm-tmp.8jv4Ap: line 45: 1370843 Aborted                 (core dumped) cargo image
error: Bad exit status from /var/tmp/rpm-tmp.8jv4Ap (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.8jv4Ap (%build)

**Comment by jialeif** [comment]
@lianghouxu  please check the fix using https://github.com/intel/tdx-tools/tree/2023ww27-update

**Comment by lianghouxu** [comment]
Worked like a charm. Thanks.
