### ISSUE TITLE
support ubuntu 20.04 build

### ISSUE THREAD

**Issue by kkbodke** [intel/tdx-tools#481]
Ubuntu 22.04 is very latest, and not all TDX features are enabled with the latest Ubuntu 22.04.

There are certain TDX features, still need Ubuntu 20.04.

Please support the Ubuntu 20.04 build.

As a general rule, we should atleast support minimum 2 versions of the distros.

**Comment by kenplusplus** [comment]
Could you please share what TDX features has the dependences on Ubuntu 20.04?

Supporting a new distro version will:
-1. Maintain addtional build script on each version of distro
-2. Maintain test compabilities on each version of distro 
-3. Run validation on each version of distro (not all tests are fulll automated)

Above 3 is very heavy and not a one-time effort.
