### ISSUE TITLE
Launch launch_td_guest.md ubuntu libvirt related error

### ISSUE THREAD

**Issue by mkbhanda** [intel/tdx-tools#486]
Links https://github.com/intel/tdx-tools/blob/2022ww49/doc/tdx_libvirt_direct.ubuntu.xml.template) or [grub boot_ubuntu](https://github.com/intel/tdx-tools/blob/2022ww49/doc/tdx_libvirt_grub.ubuntu.xml.template)

for Ubuntu guest libvirt template are missing. 
Perhaps they should point to versions in the current directory but also the names seem to have changed. Current ones have "host" in their name.
tdx_libvirt_direct.ubuntu_host.xml.template
 tdx_libvirt_grub.ubuntu_host.xml.template

**Comment by ruomengh** [comment]
@mkbhanda  Thanks for bringing up the issue.

For WW49 tag, there are libvirt xml template for both Ubuntu host ([grub boot](https://github.com/intel/tdx-tools/blob/2022ww49/doc/tdx_libvirt_grub.ubuntu_host.xml.template), [direct boot)](https://github.com/intel/tdx-tools/blob/2022ww49/doc/tdx_libvirt_direct.ubuntu_host.xml.template) and RHEL host ([grub boot](https://github.com/intel/tdx-tools/blob/2022ww49/doc/tdx_libvirt_grub.xml.template), [direct boot](https://github.com/intel/tdx-tools/blob/2022ww49/doc/tdx_libvirt_direct.xml.template))

As to the template name - they are differentiated based on host type. They all use Ubuntu guest. 

Could you please let me know where the broken link is from? I'll check and fix it.

**Comment by mkbhanda** [comment]
I used 2023ww33. If this is not latest TDX 1.0 tag, please close issue as user error.

**Comment by ruomengh** [comment]
The libvirt xml templates for 2023ww33 are located at [doc](https://github.com/intel/tdx-tools/tree/2023ww33/doc)
It's the correct tag. Gload to know it works for you. I'll close the issue.
