### ISSUE TITLE
Occasional host kernel core dump

### ISSUE THREAD

**Issue by henrysun007** [intel/tdx-tools#488]
There is core dump happenning occasionally in host. The guest can run well afterwards. 

The dmesg is attached below. The core dump happened at `9月 13 16:12:12 2023`.
[dmesg.log](https://github.com/intel/tdx-tools/files/12603143/dmesg.log)

The tag I use is `2023ww33`.

**Comment by dongx1x** [comment]
`2023ww33` is for TDX 1.0, and your kernel version is 5.19.17. The problem is that your TDX module is for TDX 1.5, which does not match the kernel, please check this.
```[三 9月 13 12:04:49 2023] tdx: TDX module: vendor_id 0x8086, major_version 1, minor_version 5, build_date 20230323, build_num 481```

**Comment by henrysun007** [comment]
The `5.19.17` version kernel is specified in [2023ww33](https://github.com/intel/tdx-tools/tree/2023ww33/build/ubuntu-22.04/intel-mvp-tdx-kernel/linux-5.19.17). So I think I need to downgrade the tdx module. What should I do? Thanks in advance.

**Comment by jialeif** [comment]
@henrysun007 Since your BIOS stitches TDX module 1.5, [2023ww27-update](https://github.com/intel/tdx-tools/releases/tag/2023ww27-update) is recommended, where TDX kernel 6.2.16 and TDX QEMU 7.2.0 work well with TDX module 1.5 .
