### ISSUE TITLE
Wrong MSR checked in check_bios_enabling_mktme

### ISSUE THREAD

**Issue by lorddoskias** [intel/tdx-tools#498]
According to the comment for this function https://github.com/intel/tdx-tools/blob/37a2387dfd5fe51abaa336aa74912c6fae772f56/utils/check-tdx-host.sh#L191C27-L191C27

msr 1401 should be checked, instead msr 0x982 is checked, the same as in function check_bios_tme_mt. So both of these functions are doing the same thing.

**Comment by kenplusplus** [comment]
@intelzhongjie

**Comment by intelzhongjie** [comment]
@lorddoskias Thanks for reporting this! The "0x1401" in the comment for check_bios_enabling_mktme is a typo. It should be 0x982 instead. Please find the details for that MSR 0x982 in the [SDM](https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html) Vol. 4 Model Specific Registers (MSRs (key words "IA_TME_ACTIVATE" or "982H").

I'll send you a PR to fix this typo for review. Thanks!
