### ISSUE TITLE
TDX module v1.5-beta doesn't build due to missing tdx_linker_script.lds

### ISSUE THREAD

**Issue by 0xabu** [intel/tdx-tools#500]
The [v1.5 beta TDX module source code release of 2023-06-22](https://www.intel.com/content/www/us/en/download/738875/intel-trust-domain-extension-intel-tdx-module.html) fails to build at the final link step with:
```
/usr/bin/ld: cannot open linker script file .../tdx-module/tdx_linker_script.lds: No such file or directory
```

The relevant linker script `tdx_linker_script.lds` appears to have been omitted from the released zip file. Thus, it's not possible to reproduce the build.

(Sorry if this is off topic. I know this is not directly related to the code in this repo, but it's not obvious where else to report the problem, and I couldn't find any reference to it online.)

**Comment by jialeif** [comment]
https://community.intel.com/t5/Intel-Trust-Domain-Extensions/bd-p/intel-tdx hope it helps
@0xabu @benschlueter
