### ISSUE TITLE
tdx1.0 kernel build fail with ubuntu-22.04

### ISSUE THREAD

**Issue by qhbqyj** [intel/tdx-tools#519]
tdx-tools-2023ww22.rdc/build/ubuntu-22.04:
WARNING: modpost: vmlinux.o(___ksymtab_gpl+acpi_tbl_allow_setup+0x0): Section mismatch in reference from the variable __ksymtab_acpi_tbl_allow_setup to the function .init.text:acpi_tbl_allow_setup()
The symbol acpi_tbl_allow_setup is exported and annotated __init 
Fix this by removing the __init annotation of acpi_tbl_allow_setup or drop the export.

  MODINFO modules.builtin.modinfo
  GEN     modules.builtin
  CC      .vmlinux.export.o
  LD      .tmp_vmlinux.btf
  BTF     .btf.vmlinux.bin.o
  LD      .tmp_vmlinux.kallsyms1
  KSYMS   .tmp_vmlinux.kallsyms1.S
  AS      .tmp_vmlinux.kallsyms1.S
  LD      .tmp_vmlinux.kallsyms2
  KSYMS   .tmp_vmlinux.kallsyms2.S
  AS      .tmp_vmlinux.kallsyms2.S
  LD      vmlinux
  BTFIDS  vmlinux
FAILED: load BTF from vmlinux: Invalid argument
make[2]: *** [/home/tdx/tdx-tools-2023ww22.rdc/build/ubuntu-22.04/intel-mvp-tdx-kernel/mvp-tdx-kernel-v5.19.17/Makefile:1168: vmlinux] Error 255
make[2]: *** Deleting file 'vmlinux'
make[2]: Leaving directory '/home/tdx/tdx-tools-2023ww22.rdc/build/ubuntu-22.04/intel-mvp-tdx-kernel/mvp-tdx-kernel-v5.19.17/debian/build/build-generic'
make[1]: *** [Makefile:219: __sub-make] Error 2
make[1]: Leaving directory '/home/tdx/tdx-tools-2023ww22.rdc/build/ubuntu-22.04/intel-mvp-tdx-kernel/mvp-tdx-kernel-v5.19.17'
make: *** [debian/rules.d/2-binary-arch.mk:53: /home/tdx/tdx-tools-2023ww22.rdc/build/ubuntu-22.04/intel-mvp-tdx-kernel/mvp-tdx-kernel-v5.19.17/debian/stamps/stamp-build-generic] Error 2

**Comment by kenplusplus** [comment]
Please try latest tag.
