### ISSUE TITLE
How to verify the kernel digest/cmdline digest？

### ISSUE THREAD

**Issue by wdsun1008** [intel/tdx-tools#525]
After completing the report verification and event log replay, how to verify if the kernel digest matches the expected value? 
I am currently using direct boot to start the TDX VM and have obtained the event log, but the kernel digest is different from the authenticode calculation result I used during TPM attestation. I noticed that the measure code for TDVF is in TdTcg2Dxe/MeasureBootPeCoff.c. Are there any relevant tools available to calculate the digest of the vmlinuz file offline?

**Comment by kenplusplus** [comment]
You can get the first time measurement as a golden value, then compare the further value with the golden value. Please check https://cloud.google.com/compute/shielded-vm/docs/shielded-vm
