### ISSUE TITLE
Create guest image fail with RHEL8.7 OS with tdx-tool 2023WW27 update

### ISSUE THREAD

**Issue by qhbqyj** [intel/tdx-tools#526]
After executing create-efi-img.sh ,we will get the following error informaion:
[  OK  ] Started Tell Plymouth To Jump To initramfs.
[  OK  ] Unmounted /mnt/sysroot/proc.
[  OK  ] Unmounted /mnt/sysroot/run.
[FAILED] Failed unmounting /run/install/repo.
[  OK  ] Unmounted /mnt/sysroot/boot/efi.
[  OK  ] Unmounted /mnt/sysroot/sys/fs/selinux.
[  OK  ] Unmounted /mnt/sysimage/dev/pts.
[  OK  ] Unmounted /mnt/sysroot/dev/shm.
         Unmounting /mnt/sysroot/sys...
[  OK  ] Unmounted /mnt/sysimage/proc.
[  OK  ] Unmounted /mnt/sysimage/sys.
[  OK  ] Unmounted /mnt/sysroot/dev/pts.
[  OK  ] Unmounted /mnt/sysimage/run.
[  OK  ] Unmounted /mnt/sysimage/sys/fs/selinux.
         Unmounting /mnt/sysroot/dev...
[  OK  ] Stopped Load/Save Random Seed.
[  OK  ] Unmounted /mnt/sysimage/dev.
[  OK  ] Unmounted /mnt/sysimage/dev/shm.
[  OK  ] Unmounted /mnt/sysimage/boot/efi.
         Unmounting /mnt/sysimage...
[  OK  ] Unmounted Temporary Directory (/tmp).
[  OK  ] Stopped target Swap.
[  OK  ] Unmounted /mnt/sysroot/dev.
[  OK  ] Unmounted /mnt/sysroot/sys.
         Unmounting /mnt/sysroot...
[  OK  ] Unmounted /mnt/sysimage.
[  OK  ] Unmounted /mnt/sysroot.
[  OK  ] Reached target Unmount All Filesystems.
[  OK  ] Stopped target Local File Systems (Pre).
[  OK  ] Stopped Create Static Device Nodes in /dev.
[  OK  ] Stopped Create System Users.
         Stopping Device-Mapper Multipath Device Controller...
[  OK  ] Stopped Remount Root and Kernel File Systems.
[  OK  ] Stopped Device-Mapper Multipath Device Controller.
[  OK  ] Reached target Shutdown.
[  OK  ] Reached target Final Step.
[  OK  ] Started Power-Off.
[  OK  ] Reached target Power-Off.
dracut Warning: Killing all remaining processes
Powering off.
[  216.877638] reboot: Power down

ERROR    Domain not found: no domain with matching uuid '67665b0e-3ec4-4813-9c2c-3294c1d82268' (td-guest-rhel-8.7)
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start td-guest-rhel-8.7
otherwise, please restart your installation.
[  OK  ] EFI image created: td-guest-rhel-8.7.qcow2
/home/tdx/tdx-tools/build/rhel-8/guest-image

**Comment by jialeif** [comment]
Skip the info and go ahead if td-guest-rhel-8.7.qcow2 has been created.
