### ISSUE TITLE
"https://github.com/intel/shim-tdx" missing the directory

### ISSUE THREAD

**Issue by kpadwal** [intel/tdx-tools#534]
/tdx-tools/build/ubuntu-22.04/intel-mvp-tdx-guest-shim$ ./build.sh
Get downstream source code...
Cloning into 'mvp-tdx-guest-shim-15.4'...
Username for 'https://github.com': kpadwal
Password for 'https://kpadwal@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/intel/shim-tdx/' not found

**Comment by kenplusplus** [comment]
https://github.com/intel/shim-tdx/ has been deleted, since all modifications have been upstream-ed. You can to use latest shim from Ubuntu 22.04 directly.

**Comment by kpadwal** [comment]
"Thank you for the update. 

Can we expect the updated script soon?"
build/ubuntu-22.04/intel-mvp-tdx-guest-shim/build.sh

**Comment by kenplusplus** [comment]
> "Thank you for the update.
> 
> Can we expect the updated script soon?" build/ubuntu-22.04/intel-mvp-tdx-guest-shim/build.sh

hmm, the old MVP stack is obsoleted/end of life, could you please use mid-stream?

**Comment by kpadwal** [comment]
Could you please help me to get the exact version of Ubuntu 22.04 version and the default Linux kernel from Ubuntu?

**Comment by kenplusplus** [comment]
> Could you please help me to get the exact version of Ubuntu 22.04 version and the default Linux kernel from Ubuntu?

could you please check https://launchpad.net/~kobuk-team/+archive/ubuntu/tdx

**Comment by kenplusplus** [comment]
@jialeif  please help to remove shim-tdx and grub-tdx, which have been deleted.

**Comment by jialeif** [comment]
Please refer to https://github.com/intel/tdx-tools/releases/tag/2023ww41
