### ISSUE TITLE
Disk encryption

### ISSUE THREAD

**Issue by pegahnikbakht** [intel/tdx-tools#547]
Hi,

Is it possible to use Azure tdx or google tdx and launch another TD VM inside the VM that has disk encryption enabled? or it should be on a bare metal host with TDX support?

Regards,
Pegah

**Comment by ruomengh** [comment]
Thanks for raising the issue. The project is end of life. Please refer to Red Hat blog [Enabling hardware-backed confidential computing with a CentOS SIG](https://www.redhat.com/en/blog/enabling-hardware-backed-confidential-computing-centos-sig) or Ubuntu blog [Intel® TDX 1.0 technology preview available on Ubuntu 23.10](https://ubuntu.com/blog/intel-tdx-1-0-preview-on-ubuntu-23-10) or SUSE blog [Intel® TDX Support Coming to SUSE Linux Enterprise Server](https://www.suse.com/c/intel-tdx-support-coming-to-suse-linux-enterprise-server/) for more information of TDX Early Preview.
