### ISSUE TITLE
Inquiry Regarding dma_alloc_coherent() Behavior in Intel TDX 1.5 and Canonical 6.5 Fork

### ISSUE THREAD

**Issue by kpadwal** [intel/tdx-tools#550]
I have been using the dma_alloc_coherent() API to allocate memory and marked it as shared pages with read/write access. This worked as expected when performing the dma from the device to read and write with Intel TDX 1.0 and Intel's 6.2 (2023ww15) fork.

 However, we encountered an issue after transitioning to the Canonical 6.5 TDX fork + Intel TDX 1.5. We are only able to read from shared pages once, but we are not able to write on the same page. However, we are able to write to a different page.

Are there any changes expected for dma_alloc_coherent() for TDX 1.5 or 6.5 Linux kernel? There are no error messages on the guest or host dmesg. 

Do you have any suggestions or pointers to help resolve this issue?

Canonical 6.5 TDX fork - https://github.com/canonical/tdx

**Comment by ruomengh** [comment]
Thanks for raising the issue. The project is end of life. Please refer to Red Hat blog [Enabling hardware-backed confidential computing with a CentOS SIG](https://www.redhat.com/en/blog/enabling-hardware-backed-confidential-computing-centos-sig) or Ubuntu blog [Intel® TDX 1.0 technology preview available on Ubuntu 23.10](https://ubuntu.com/blog/intel-tdx-1-0-preview-on-ubuntu-23-10) or SUSE blog [Intel® TDX Support Coming to SUSE Linux Enterprise Server](https://www.suse.com/c/intel-tdx-support-coming-to-suse-linux-enterprise-server/) for more information of TDX Early Preview.
