### ISSUE TITLE
RHEL 9.1 with Intel TDX kernel compilation results in an error

### ISSUE THREAD

**Issue by prasadkrishnak** [intel/tdx-tools#551]
Hello, I've a system with RHEL 9.1 installed and have the tdx-tools from tdx-1.5 branch downloaded. Upon compiling /tdx-tools/build/rhel-9/intel-mvp-tdx-kernel/linux-tdx-kernel, it results in the following error when we've CONFIG_INTEL_TDX_HOST set to yes in the kernel config file. 

Am I missing something here ? 

WARNING: modpost: EXPORT symbol "__seamcall" [vmlinux] version generation failed, symbol will not be versioned.
Is "__seamcall" prototyped in <asm/asm-prototypes.h>?
WARNING: modpost: "__seamcall" [arch/x86/kvm/kvm-intel.ko] has no CRC!
  CC      .vmlinux.export.o
  UPD     include/generated/utsversion.h
  CC      init/version-timestamp.o
  LD      .tmp_vmlinux.btf
ld: arch/x86/coco/tdx/tdx-rtmr.o: in function `ima_extend_rtmr':
/root/tdx-tools/build/rhel-9/intel-mvp-tdx-kernel/linux-tdx-kernel/arch/x86/coco/tdx/tdx-rtmr.c:80: undefined reference to `ccel_record_eventlog'
  BTF     .btf.vmlinux.bin.o
pahole: .tmp_vmlinux.btf: No such file or directory
  LD      .tmp_vmlinux.kallsyms1
.btf.vmlinux.bin.o: file not recognized: file format not recognized
make[1]: *** [scripts/Makefile.vmlinux:35: vmlinux] Error 1
make: *** [Makefile:1264: vmlinux] Error 2

**Comment by ruomengh** [comment]
Thanks for raising the issue. The project is end of life. Please refer to Red Hat blog [Enabling hardware-backed confidential computing with a CentOS SIG](https://www.redhat.com/en/blog/enabling-hardware-backed-confidential-computing-centos-sig) or Ubuntu blog [Intel® TDX 1.0 technology preview available on Ubuntu 23.10](https://ubuntu.com/blog/intel-tdx-1-0-preview-on-ubuntu-23-10) or SUSE blog [Intel® TDX Support Coming to SUSE Linux Enterprise Server](https://www.suse.com/c/intel-tdx-support-coming-to-suse-linux-enterprise-server/) for more information of TDX Early Preview.
