### ISSUE TITLE
distribute pre-built binaries

### ISSUE THREAD

**Issue by matti** [intel/tdx-tools#83]
would be so much easier to try out tdx

suggestion: use github packages.

**Comment by kenplusplus** [comment]
Thanks Matti's suggestion, till now, we have no plan to release prebuild binary:
1. We hope community can get the patches for exploration and porting.
2. We are trying to upstream these patches step by step, then we can remove these downstream packages.
3. For these temporary downstream packages, we could not provide full CVE/security fixing (not related to TDX).
