### ISSUE TITLE
where to get TDX SEAM Module intel-mvp-tdx-module-spr

### ISSUE THREAD

**Issue by matti** [intel/tdx-tools#86]
README says:

> _NOTE_: Please get separated RPM for signed build `TDX SEAM Module` and install via `sudo dnf install intel-mvp-tdx-module-spr`."

Where do I get this module?

I've already built everything and hacked distribution through dockerhub (while waiting for #83)

```
docker create --name intel-tdx-tools-repo mattipaksula/intel-tdx-tools-repo true
docker cp intel-tdx-tools-repo:/host /srv/tdx-host
docker cp intel-tdx-tools-repo:/guest /srv/tdx-guest

echo """[tdx-host-local]
name=tdx-host-local
baseurl=file:///srv/tdx-host
enabled=1
gpgcheck=0
module_hotfixes=true""" > /etc/yum.repos.d/tdx-host-local.repo

sudo dnf install intel-mvp-spr-kernel intel-mvp-tdx-tdvf intel-mvp-spr-qemu-kvm intel-mvp-tdx-libvirt

# separate signed module whatever it means
# sudo dnf install intel-mvp-tdx-module-spr ??
```

**Comment by kenplusplus** [comment]
TDX module's source: https://github.com/intel/tdx-module
TDX SEAM loader's source: https://github.com/intel/seam-loader
But it need be signed by Intel till now, so it is only avaialble for limited customers.

**Comment by matti** [comment]
What hardware is required to even run this? Unreleased Sapphire Rapids?

**Comment by kenplusplus** [comment]
Yes, it is Sapphire Rapids, Please see 
- Intel Offical Specification at https://www.intel.com/content/www/us/en/developer/articles/technical/intel-trust-domain-extensions.html
- https://www.phoronix.com/scan.php?page=news_item&px=Intel-TDX-Compiler-Support

**Comment by matti** [comment]
a warning in the README would be nice

**Comment by kenplusplus** [comment]
> a warning in the README would be nice

Great idea! Thanks. I will submit PR to address this for your review.

**Comment by matti** [comment]
@kenplusplus where to reach out for an early adopters program to get an early access as soon as it is possible?

**Comment by kenplusplus** [comment]
> 

@matti  Good question, will try to ask and reply here once get confirmed answer.

**Comment by kenplusplus** [comment]
@matti Sorry, Intel doesn’t have plans for a public developer cloud for TDX **prior to Sapphire Rapids launch**.

**Comment by matti** [comment]
@kenplusplus thanks - what would be the best developer program or such to get hands on on the launch day?

eg. how to get access to the hardware so that I can further contribute here

**Comment by kenplusplus** [comment]
@matti Sorry, I don’t have any additional info to share at this time

**Comment by RainCat1998** [comment]
> Please see
> 
> * Intel Offical Specification at https://www.intel.com/content/www/us/en/developer/articles/technical/intel-trust-domain-extensions.html
> * https://www.phoronix.com/scan.php?page=news_item&px=Intel-TDX-Compiler-Support

Will you provide a simulation environment for TDX like SGX simulation mode ?

**Comment by kenplusplus** [comment]
> 

Do you mean [Gramine ](https://github.com/gramineproject/gramine) based LibOS support pure software or SGX enclave backend?
I think there is no such simulation for TDX, which is the encryption for VM.  Without TDX hardware support, you still can use Intel MK-TME to protect VM, for example <https://www.linux-kvm.org/images/d/d7/Mktme_kvm_forum_2018.pdf>

**Comment by RainCat1998** [comment]
> > 
> 
> Do you mean [Gramine ](https://github.com/gramineproject/gramine) based LibOS support pure software or SGX enclave backend? I think there is no such simulation for TDX, which is the encryption for VM. Without TDX hardware support, you still can use Intel MK-TME to protect VM, for example https://www.linux-kvm.org/images/d/d7/Mktme_kvm_forum_2018.pdf

I mean "The simulation mode" in sgx sdk. It's useful for debuging & testing without hardware sgx support.
Since Sapphire Rapids are not released yet, we cannot test TDX without hardware support. So I just asked if there were any simulation solution for someone who doesn't have a TDX ready CPU.

**Comment by kenplusplus** [comment]
> > > 
> > 
> > 
> > Do you mean [Gramine ](https://github.com/gramineproject/gramine) based LibOS support pure software or SGX enclave backend? I think there is no such simulation for TDX, which is the encryption for VM. Without TDX hardware support, you still can use Intel MK-TME to protect VM, for example https://www.linux-kvm.org/images/d/d7/Mktme_kvm_forum_2018.pdf
> 
> I mean "The simulation mode" in sgx sdk. It's useful for debuging & testing without hardware sgx support. Since Sapphire Rapids are not released yet, we cannot test TDX without hardware support. So I just asked if there were any simulation solution for someone who doesn't have a TDX ready CPU.

Thanks for your clarification, as far as I know, there is not simulation SDK or solution for TDX.

**Comment by aep** [comment]
> Since Sapphire Rapids are not released yet

Sapphire Rapids is now available but nowhere does it say if they have TDX.
Is there another chip coming or is that the thing now?

**Comment by matti** [comment]
@aep its available in theory, can't buy it anywhere.

**Comment by matti** [comment]
Basically no Sapphire Rapids supports TDX - Emerald Rapids will, see https://github.com/intel/tdx-tools/issues/399
